In [ ]:
#question 1

In [15]:
import numpy as np
a=np.array([[1,5],[10,15]])
b=a.tolist()
print(b)


[[1, 5], [10, 15]]


In [ ]:
#question 2

In [22]:
import numpy as np
a=np.array([[1, 5, 6],
            [10,15,8],
            [1, 2, 3]])
b=a.trace()
print(b)



19


In [ ]:
#question 3

In [39]:
import numpy as np
a = np.array([[1,2],[3,5]])
x=2
b=a>x
print(b)

[[False False]
 [ True  True]]


In [ ]:
#question 4

In [3]:
import numpy as np
a= np.array ([[1,3],[2, 5]])
b= np.array ([[2,6],[5,6]])
c= a + b
print(c)


[[ 3  9]
 [ 7 11]]


In [ ]:
#question 5

In [11]:
import numpy as np
a=np.array ([[1,2,3],
             [2,4,6],
             [3,5,7]])
b=a-np.mean(a,axis=1)
print(b)

[[-1. -2. -2.]
 [ 0.  0.  1.]
 [ 1.  1.  2.]]
